

import word.api.interfaces.IDocument;
import word.w2004.Document2004;
import word.w2004.elements.BreakLine;
import word.w2004.elements.Heading1;
import word.w2004.elements.Heading2;
import word.w2004.elements.Heading3;
import word.w2004.elements.Paragraph;
import word.w2004.elements.ParagraphPiece;
import word.w2004.elements.TableV2;
import word.w2004.elements.tableElements.TableCell;
import word.w2004.elements.tableElements.TableRow;
import word.w2004.style.Font;
import word.w2004.style.HeadingStyle.Align;


public class Word {

	public void run(){
		IDocument myDoc = new Document2004();
        TableV2 tbl = new TableV2();
        
        tbl.addRow( TableRow.with("Table Header in all Pages", "Usefull for reports").withStyle().repeatTableHeaderOnEveryPage().create() );
        
        tbl.addRow( TableRow.with("Simple String cell", "Another simple String cell") ); 
        tbl.addRow( TableRow.with( TableCell.with(Paragraph.with("TableCell- Style to the whole cell, Par").create()), "Simple String" ).withStyle().bold().create() );
        tbl.addRow( TableRow.with("Style to the whole cell, Str", "String").withStyle().bold().create() );
        tbl.addRow( TableRow.with( TableCell.with(Paragraph.with("TableRowV2 with merge").create()).withStyle().gridSpan(2).create() ).withStyle().bold().create() );
        tbl.addRow( TableRow.with( TableCell.with(Paragraph.withPieces( ParagraphPiece.with("Paragraph with Style inside TableCell").withStyle().bold().fontSize("20").create() ).create()).withStyle().bgColor("00FFFF").create(), "String"  ));
        
        //String img = Image.from_WEB_URL("http://www.google.com/images/logos/ps_logo2.png").setHeight("100").setWidth("300").create().getContent();
        //tbl.addRow( TableRow.with("this google logo: ", "Image here: "+ img + " == image before") );
        // Headings
        myDoc.addEle(Heading1.with("===== Java2word ======").create());
        myDoc.addEle(Heading2.with("===== Headings ======").create());
        myDoc.addEle(Paragraph
                .with("This doc has been generated by the unit test testJava2wordAllInOne() in the class DocumentTest2004Test.java.")
                .create());
        myDoc.addEle(BreakLine.times(1).create());

        myDoc.addEle(Paragraph
                .with("I will try to use a little bit of everything in the API Java2word. "
                        + "I realised that is very dificult to keep the doucmentation updated "
                        + "so this is where I will demostrate how to do some cool things with Java2word!")
                .create());

        myDoc.addEle(Heading1.with("Heading01 without styling").create());
        myDoc.addEle(Heading2.with("Heading02 with style Center").withStyle()
                .align(Align.CENTER).italic().create());
        myDoc.addEle(Heading3.with("Heading03 aligned Right").withStyle().bold()
                .align(Align.RIGHT).create());
        
        // Paragraph and ParagrapPiece
        myDoc.addEle(Heading2.with("===== Paragraph and ParagrapPiece ======")
                .create());
        myDoc.addEle(Paragraph.with("I am a very simple paragraph.").create());

        myDoc.addEle(BreakLine.times(1).create());
        ParagraphPiece myParPiece01 = ParagraphPiece
                .with("If you use the class 'Paragraph', you will have limited style. Maybe only paragraph Aligment or BgColor.");
        ParagraphPiece myParPiece02 = ParagraphPiece
                .with("In order to use more advanced style, you have to use ParagraphPiece");
        ParagraphPiece myParPiece03 = ParagraphPiece
                .with("One example of this is when you want to make ONLY one word BOLD or ITALIC. the way to to this is create many pieces, format them separetely and put all together in a Paragraph object. Example:");

        myDoc.addEle(Paragraph.withPieces(myParPiece01, myParPiece02,
                myParPiece03).create());

        ParagraphPiece myParPieceJava = ParagraphPiece.with("I like Java and ")
                .withStyle().font(Font.COURIER).create();
        ParagraphPiece myParPieceRuby = ParagraphPiece.with("Ruby!!! ")
                .withStyle().bold().italic().create();
        ParagraphPiece myParPieceAgile = ParagraphPiece
                .with("I actually like Java, Ruby Agile, BDD, Cucumber... ")
                .withStyle().textColor("008000").create();

        myDoc.addEle(Paragraph.withPieces(myParPieceJava, myParPieceRuby,
                myParPieceAgile).create());

        myDoc.addEle(BreakLine.times(2).create());
        myDoc.addEle(Paragraph.withPieces(
                ParagraphPiece.with("This is a manual 'bold' and 'italic'")
                        .withStyle().font(Font.COURIER).bold().italic()
                        .create()).create());
        myDoc.addEle(Paragraph
                .withPieces(
                        ParagraphPiece
                                .with("This is the SAME as the above line but with 'Smart' Bold/Italic ")
                                .withStyle().font(Font.COURIER_BOLD_ITALIC)
                                .create()).create());
        myDoc.addEle(BreakLine.times(1).create());

        // font size
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("No size")
                .create(), ParagraphPiece.with(" but I am size 24.").withStyle()
                .fontSize("24").create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Subscript").withStyle().subscript().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Superscript").withStyle().superscript().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Strike").withStyle().strike().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Caps").withStyle().caps().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("SmallCaps").withStyle().smallCaps().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("DoubleStrike").withStyle().doubleStrike().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Emboss").withStyle().emboss().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Imprint").withStyle().imprint().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Outline").withStyle().outline().create()));
        myDoc.addEle(Paragraph.withPieces(ParagraphPiece.with("The Style is: ").create(), ParagraphPiece.with("Shadow").withStyle().shadow().create()));
        /*
        Table tbl12 = new Table();
        tbl12.addTableEle(TableEle.TH, "Name", "Number of gols", "Country");

        tbl12.addTableEle(TableEle.TD, "* Arthur Friedenreich", "1329", "Brazil");
        tbl12.addTableEle(TableEle.TD, "Pele", "1281", "Brazil");
        tbl12.addTableEle(TableEle.TD, "Romario", "1002", "Brazil");
        tbl12.addTableEle(TableEle.TD, "Tulio Maravilha", "956", "Brazil");
        tbl12.addTableEle(TableEle.TD, "** Zico", "815", "Brazil");
        tbl12.addTableEle(TableEle.TD, "Roberto Dinamite", "748", "Brazil");
        tbl12.addTableEle(TableEle.TD, "Di Stéfano", "715", "Argentina");
        tbl12.addTableEle(TableEle.TD, "Puskas", "689", "Hungary");
        tbl12.addTableEle(TableEle.TD, "Flávio", "591", "Brazil");
        tbl12.addTableEle(TableEle.TD, "James McGory", "550", "Scotland");
        tbl12.addTableEle(TableEle.TD, "*** Leonardo Correa", "299", "Brazil/Australia");
        tbl12.addTableEle(TableEle.TD, "Maradona", "258", "Argentina");

        tbl12.addTableEle(TableEle.TF, "Total", "1,100,000.00", " ");

        myDoc.addEle(tbl12);
        */     
	}

}
